
package eus.ehu.informatica.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import eus.ehu.informatica.ws.interfaces.LibroArray;
import eus.ehu.informatica.ws.interfaces.LibroRespuesta;
import eus.ehu.informatica.ws.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILibroWS", targetNamespace = "http://interfaces.ws.informatica.ehu.eus/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILibroWS {


    /**
     * 
     * @param isbn
     * @return
     *     returns eus.ehu.informatica.ws.interfaces.LibroRespuesta
     */
    @WebMethod
    @WebResult(name = "libro", partName = "libro")
    @Action(input = "http://interfaces.ws.informatica.ehu.eus/ILibroWS/obtenerPorISBNRequest", output = "http://interfaces.ws.informatica.ehu.eus/ILibroWS/obtenerPorISBNResponse")
    public LibroRespuesta obtenerPorISBN(
        @WebParam(name = "isbn", partName = "isbn")
        String isbn);

    /**
     * 
     * @return
     *     returns eus.ehu.informatica.ws.interfaces.LibroArray
     */
    @WebMethod
    @WebResult(name = "listaLibros", partName = "listaLibros")
    @Action(input = "http://interfaces.ws.informatica.ehu.eus/ILibroWS/obtenerListadoLibrosRequest", output = "http://interfaces.ws.informatica.ehu.eus/ILibroWS/obtenerListadoLibrosResponse")
    public LibroArray obtenerListadoLibros();

}
