
package eus.ehu.informatica.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibroWSImpService", targetNamespace = "http://ws.informatica.ehu.eus/", wsdlLocation = "http://localhost:8080/jax-ws-auth/libroservice?wsdl")
public class LibroWSImpService
    extends Service
{

    private final static URL LIBROWSIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBROWSIMPSERVICE_EXCEPTION;
    private final static QName LIBROWSIMPSERVICE_QNAME = new QName("http://ws.informatica.ehu.eus/", "LibroWSImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax-ws-auth/libroservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBROWSIMPSERVICE_WSDL_LOCATION = url;
        LIBROWSIMPSERVICE_EXCEPTION = e;
    }

    public LibroWSImpService() {
        super(__getWsdlLocation(), LIBROWSIMPSERVICE_QNAME);
    }

    public LibroWSImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBROWSIMPSERVICE_QNAME, features);
    }

    public LibroWSImpService(URL wsdlLocation) {
        super(wsdlLocation, LIBROWSIMPSERVICE_QNAME);
    }

    public LibroWSImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBROWSIMPSERVICE_QNAME, features);
    }

    public LibroWSImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibroWSImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILibroWS
     */
    @WebEndpoint(name = "LibroWSImpPort")
    public ILibroWS getLibroWSImpPort() {
        return super.getPort(new QName("http://ws.informatica.ehu.eus/", "LibroWSImpPort"), ILibroWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILibroWS
     */
    @WebEndpoint(name = "LibroWSImpPort")
    public ILibroWS getLibroWSImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.informatica.ehu.eus/", "LibroWSImpPort"), ILibroWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBROWSIMPSERVICE_EXCEPTION!= null) {
            throw LIBROWSIMPSERVICE_EXCEPTION;
        }
        return LIBROWSIMPSERVICE_WSDL_LOCATION;
    }

}
