
package com.ipartek.formacion.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CandidatoWSImplService", targetNamespace = "http://webservice.formacion.ipartek.com/", wsdlLocation = "http://localhost:8080/jax-ws-list/candidatows?wsdl")
public class CandidatoWSImplService
    extends Service
{

    private final static URL CANDIDATOWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CANDIDATOWSIMPLSERVICE_EXCEPTION;
    private final static QName CANDIDATOWSIMPLSERVICE_QNAME = new QName("http://webservice.formacion.ipartek.com/", "CandidatoWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax-ws-list/candidatows?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANDIDATOWSIMPLSERVICE_WSDL_LOCATION = url;
        CANDIDATOWSIMPLSERVICE_EXCEPTION = e;
    }

    public CandidatoWSImplService() {
        super(__getWsdlLocation(), CANDIDATOWSIMPLSERVICE_QNAME);
    }

    public CandidatoWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANDIDATOWSIMPLSERVICE_QNAME, features);
    }

    public CandidatoWSImplService(URL wsdlLocation) {
        super(wsdlLocation, CANDIDATOWSIMPLSERVICE_QNAME);
    }

    public CandidatoWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANDIDATOWSIMPLSERVICE_QNAME, features);
    }

    public CandidatoWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CandidatoWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CandidatoWSInterface
     */
    @WebEndpoint(name = "CandidatoWSImplPort")
    public CandidatoWSInterface getCandidatoWSImplPort() {
        return super.getPort(new QName("http://webservice.formacion.ipartek.com/", "CandidatoWSImplPort"), CandidatoWSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CandidatoWSInterface
     */
    @WebEndpoint(name = "CandidatoWSImplPort")
    public CandidatoWSInterface getCandidatoWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.formacion.ipartek.com/", "CandidatoWSImplPort"), CandidatoWSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANDIDATOWSIMPLSERVICE_EXCEPTION!= null) {
            throw CANDIDATOWSIMPLSERVICE_EXCEPTION;
        }
        return CANDIDATOWSIMPLSERVICE_WSDL_LOCATION;
    }

}
