
package com.ipartek.formacion.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.ipartek.formacion.webservice.interfaz.Candidato;
import com.ipartek.formacion.webservice.interfaz.CandidatoArray;
import com.ipartek.formacion.webservice.interfaz.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CandidatoWSInterface", targetNamespace = "http://interfaz.webservice.formacion.ipartek.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CandidatoWSInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/updateRequest", output = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/updateResponse")
    public int update(
        @WebParam(name = "arg0", partName = "arg0")
        Candidato arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/deleteRequest", output = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/deleteResponse")
    public int delete(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/createRequest", output = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/createResponse")
    public int create(
        @WebParam(name = "arg0", partName = "arg0")
        Candidato arg0);

    /**
     * 
     * @return
     *     returns com.ipartek.formacion.webservice.interfaz.CandidatoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/getAllRequest", output = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/getAllResponse")
    public CandidatoArray getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.formacion.webservice.interfaz.Candidato
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/getByIdRequest", output = "http://interfaz.webservice.formacion.ipartek.com/CandidatoWSInterface/getByIdResponse")
    public Candidato getById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
