
package com.ipartek.formacion.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://interfaz.webservice.formacion.ipartek.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaz.webservice.formacion.ipartek.com/WebServiceInterface/printMessageRequest", output = "http://interfaz.webservice.formacion.ipartek.com/WebServiceInterface/printMessageResponse")
    public String printMessage();

}
